// Local ES→EN dictionary. Lookup is case-insensitive; accented and
// unaccented forms are both indexed so "tambien" finds "también".

const DICT = {
  // ── Articles / Determiners ────────────────────────────────────────
  el: 'the / he', la: 'the / her', los: 'the (plural)',
  las: 'the (plural / feminine)', un: 'a / an', una: 'a / an',
  unos: 'some', unas: 'some',

  // ── Subject / Object Pronouns ────────────────────────────────────
  yo: 'I', tu: 'you / your', ella: 'she',
  nosotros: 'we', ellos: 'they', ellas: 'they (female)',
  usted: 'you (formal)', ustedes: 'you all',
  me: 'me / myself', te: 'you / yourself',
  se: 'himself / herself / themselves / reflexive',
  nos: 'us / ourselves', le: 'him / her (indirect)',
  les: 'them (indirect)', lo: 'it / him', mi: 'my', mis: 'my (plural)',
  tus: 'your (plural)', su: 'his / her / their / your (formal)',
  sus: 'his / her / their (plural)',
  nuestro: 'our', nuestra: 'our (feminine)',
  nuestros: 'our (plural)', nuestras: 'our (plural feminine)',
  este: 'this / this one (masculine)',
  esta: 'this / he is / she is',
  estos: 'these', estas: 'these / you are',
  ese: 'that', esa: 'that (feminine)',
  esos: 'those', esas: 'those (feminine)',
  aquel: 'that (over there)', aquella: 'that one (over there)',
  que: 'that / what / which', quien: 'who', quienes: 'who (plural)',
  cual: 'which', cuales: 'which ones',
  donde: 'where', cuando: 'when',
  como: 'like / as / how', cuanto: 'how much', cuantos: 'how many',
  conmigo: 'with me', contigo: 'with you',

  // ── Prepositions ──────────────────────────────────────────────────
  a: 'to / at', de: 'of / from', en: 'in / on / at',
  con: 'with', sin: 'without', por: 'for / by / through',
  para: 'for / to / in order to', sobre: 'about / on / above',
  entre: 'between / among', bajo: 'under / below / bass',
  desde: 'from / since', hasta: 'until / up to / even',
  hacia: 'toward', segun: 'according to',
  durante: 'during', tras: 'after / behind',

  // ── Conjunctions ──────────────────────────────────────────────────
  y: 'and', e: 'and', o: 'or', u: 'or', pero: 'but',
  sino: 'but rather', ni: 'neither / nor',
  porque: 'because', aunque: 'although / even though',
  si: 'if / yes', pues: 'well / since / then',
  mientras: 'while', mas: 'more / but',

  // ── Verb infinitives ──────────────────────────────────────────────
  ser: 'to be (permanent)', estar: 'to be (location/state)',
  tener: 'to have', hacer: 'to do / to make',
  ir: 'to go', venir: 'to come', decir: 'to say / to tell',
  ver: 'to see', saber: 'to know', querer: 'to want / to love',
  poder: 'to be able to / can', poner: 'to put',
  salir: 'to leave / to go out', llevar: 'to carry / to wear',
  dar: 'to give', traer: 'to bring', hablar: 'to speak',
  comer: 'to eat', vivir: 'to live', pensar: 'to think',
  sentir: 'to feel', dormir: 'to sleep', perder: 'to lose',
  encontrar: 'to find', buscar: 'to look for',
  dejar: 'to leave / to let', pasar: 'to pass / to happen',
  seguir: 'to follow / to continue', llamar: 'to call',
  llegar: 'to arrive', volver: 'to return', creer: 'to believe',
  entrar: 'to enter', trabajar: 'to work', necesitar: 'to need',
  parecer: 'to seem', conocer: 'to know (a person)',
  empezar: 'to start', esperar: 'to wait / to hope',
  recordar: 'to remember', olvidar: 'to forget',
  ayudar: 'to help', cambiar: 'to change', amar: 'to love',
  bailar: 'to dance', cantar: 'to sing', tocar: 'to touch / to play',
  mirar: 'to look / to watch', escuchar: 'to listen',
  caminar: 'to walk', correr: 'to run', caer: 'to fall',
  morir: 'to die', nacer: 'to be born', crecer: 'to grow',
  jugar: 'to play', ganar: 'to win / to earn',
  comprar: 'to buy', vender: 'to sell',
  abrir: 'to open', cerrar: 'to close',
  leer: 'to read', escribir: 'to write',
  aprender: 'to learn', tomar: 'to take / to drink',
  beber: 'to drink', gritar: 'to shout', llorar: 'to cry',
  reir: 'to laugh', sonreir: 'to smile',
  abrazar: 'to hug', besar: 'to kiss',
  luchar: 'to fight', pelear: 'to fight / to argue',
  gastar: 'to spend', sonar: 'to dream / to sound',
  rezar: 'to pray', faltar: 'to be missing', importar: 'to matter',
  gustar: 'to like (pleases)', encantar: 'to love (enchants)',
  doler: 'to hurt / to ache', mover: 'to move',
  subir: 'to go up', bajar: 'to go down',
  entender: 'to understand', comprender: 'to understand',
  contar: 'to count / to tell', mostrar: 'to show',
  quitar: 'to remove', agarrar: 'to grab / to hold',
  soltar: 'to release', prender: 'to turn on',
  apagar: 'to turn off', extranar: 'to miss (someone)',
  sufrir: 'to suffer', disfrutar: 'to enjoy',
  volar: 'to fly', nadar: 'to swim', saltar: 'to jump',
  jalar: 'to pull / to like (Mexican slang)',
  pistear: 'to drink / to party (Mexican slang)',
  perrear: 'to dance reggaeton style',
  chambear: 'to work (Mexican slang)',
  cobrar: 'to charge / collect', ahorrar: 'to save (money)',
  haber: 'to have (auxiliary)',

  // ── Present tense (yo) ────────────────────────────────────────────
  soy: 'I am', estoy: 'I am (at/feeling)', tengo: 'I have',
  voy: 'I go / I am going', quiero: 'I want / I love', puedo: 'I can',
  digo: 'I say', hago: 'I do / I make',
  pongo: 'I put', vengo: 'I come', salgo: 'I leave',
  llevo: 'I carry / I wear', pienso: 'I think', siento: 'I feel',
  veo: 'I see', doy: 'I give', traigo: 'I bring',
  hablo: 'I speak', canto: 'I sing / he/she sang',
  llamo: 'I call / he/she called',
  llego: 'I arrive / he/she arrived',
  creo: 'I believe', paso: 'I pass / step / it happened',
  dejo: 'I leave / I let / he/she left',
  busco: 'I look for', sigo: 'I follow', vuelvo: 'I return',
  encuentro: 'I find', camino: 'I walk / road / path',
  corro: 'I run', caigo: 'I fall', muevo: 'I move',
  vuelo: 'I fly / flight', recuerdo: 'I remember / memory',
  olvido: 'I forget / he/she forgot', lloro: 'I cry / he/she cried',
  grito: 'I shout', beso: 'kiss / I kiss', abrazo: 'hug / I hug',
  bailo: 'I dance / he/she danced',

  // ── Present tense (tú) ───────────────────────────────────────────
  eres: 'you are', tienes: 'you have',
  vas: 'you go', quieres: 'you want', puedes: 'you can',
  sabes: 'you know', dices: 'you say', haces: 'you do',
  pones: 'you put', vienes: 'you come', sales: 'you leave',
  llevas: 'you carry', piensas: 'you think', sientes: 'you feel',
  ves: 'you see', das: 'you give', traes: 'you bring',
  hablas: 'you speak', bailas: 'you dance', cantas: 'you sing',
  llamas: 'you call', llegas: 'you arrive', crees: 'you believe',
  pasas: 'you pass', dejas: 'you leave', buscas: 'you look for',
  sigues: 'you follow', vuelves: 'you return', encuentras: 'you find',
  caminas: 'you walk', corres: 'you run', recuerdas: 'you remember',
  olvidas: 'you forget', extranas: 'you miss',

  // ── Present tense (él/ella) ───────────────────────────────────────
  es: 'is / he is / she is',
  tiene: 'he/she has', va: 'he/she goes',
  viene: 'he/she comes', sale: 'he/she leaves',
  lleva: 'he/she carries / wears', piensa: 'he/she thinks',
  siente: 'he/she feels', da: 'he/she gives',
  trae: 'he/she brings', habla: 'he/she speaks',
  baila: 'he/she dances', luce: 'he/she looks / shines',
  dice: 'he/she says', hace: 'he/she does', puede: 'he/she can',
  pone: 'he/she puts', sabe: 'he/she knows',
  mueve: 'he/she moves', vuela: 'he/she flies',
  recuerda: 'he/she remembers', olvida: 'he/she forgets',
  corre: 'he/she runs / run! (command)', busca: 'he/she looks for',
  deja: 'he/she leaves', pasa: 'it happens / he/she passes',
  sigue: 'he/she follows', vuelve: 'he/she returns',
  encuentra: 'he/she finds',

  // ── Present tense (nosotros) ─────────────────────────────────────
  somos: 'we are', estamos: 'we are (at/feeling)', tenemos: 'we have',
  vamos: "let's go / we go", queremos: 'we want', podemos: 'we can',
  sabemos: 'we know', decimos: 'we say', hacemos: 'we do',
  ponemos: 'we put', venimos: 'we come', salimos: 'we leave',
  llevamos: 'we carry', pensamos: 'we think', sentimos: 'we feel',
  damos: 'we give', hablamos: 'we speak', bailamos: 'we dance',
  cantamos: 'we sing', llegamos: 'we arrive', creemos: 'we believe',
  seguimos: 'we follow', volvemos: 'we return',

  // ── Present tense (ellos) ─────────────────────────────────────────
  son: 'they are', estan: 'they are', tienen: 'they have',
  quieren: 'they want', pueden: 'they can', saben: 'they know',
  dicen: 'they say', hacen: 'they do', ponen: 'they put',
  vienen: 'they come', salen: 'they leave', llevan: 'they carry',
  piensan: 'they think', sienten: 'they feel', ven: 'they see / come! (command)',
  dan: 'they give', traen: 'they bring', hablan: 'they speak',
  bailan: 'they dance', cantan: 'they sing', llaman: 'they call',
  llegan: 'they arrive', creen: 'they believe', pasan: 'they pass',
  dejan: 'they leave', buscan: 'they look for',
  siguen: 'they follow', vuelven: 'they return',

  // ── Preterite (common) ───────────────────────────────────────────
  fui: 'I was / I went', fuiste: 'you were / went',
  fue: 'he/she was / went', fuimos: 'we went', fueron: 'they went',
  era: 'I/he/she was (before)', eras: 'you were', eran: 'they were',
  tuve: 'I had', tuviste: 'you had', tuvo: 'he/she had',
  tuvieron: 'they had', hice: 'I did', hiciste: 'you did',
  hizo: 'he/she did', hicieron: 'they did',
  dije: 'I said', dijiste: 'you said', dijo: 'he/she said',
  dijeron: 'they said', vine: 'I came', viniste: 'you came',
  vino: 'he/she came / wine', vinieron: 'they came',
  puse: 'I put', puso: 'he/she put', pusieron: 'they put',
  quise: 'I wanted', quiso: 'he/she wanted',
  pude: 'I could', pudo: 'he/she could',
  supe: 'I found out', supo: 'he/she knew',
  vi: 'I saw', viste: 'you saw', vio: 'he/she saw',
  vimos: 'we saw', vieron: 'they saw',
  di: 'I gave / say! (command)', dio: 'he/she gave', dieron: 'they gave',
  estuve: 'I was', estuvo: 'he/she was', estuvieron: 'they were',
  bailaron: 'they danced', cantaron: 'they sang',
  llamaron: 'they called', llegaron: 'they arrived',
  perdio: 'he/she lost', perdieron: 'they lost',
  dejaron: 'they left', pasaron: 'they passed',
  olvide: 'I forgot', recorde: 'I remembered', llore: 'I cried',
  cayo: 'he/she fell',

  // ── Future (common) ──────────────────────────────────────────────
  sera: 'it will be', sere: 'I will be', seran: 'they will be',
  tendre: 'I will have', tendra: 'he/she will have',
  hare: 'I will do', hara: 'he/she will do',
  ire: 'I will go', ira: 'he/she will go',
  vendre: 'I will come', vendra: 'he/she will come',
  podre: 'I will be able', podra: 'he/she will be able',
  sabre: 'I will know', sabra: 'he/she will know',
  saldre: 'I will leave', saldra: 'he/she will leave',

  // ── Gerunds ───────────────────────────────────────────────────────
  siendo: 'being', estando: 'being (at/feeling)', teniendo: 'having',
  haciendo: 'doing / making', yendo: 'going', viniendo: 'coming',
  diciendo: 'saying', viendo: 'seeing', sabiendo: 'knowing',
  queriendo: 'wanting', poniendo: 'putting', saliendo: 'going out',
  llevando: 'carrying', dando: 'giving', hablando: 'speaking',
  comiendo: 'eating', viviendo: 'living', pensando: 'thinking',
  sintiendo: 'feeling', durmiendo: 'sleeping', perdiendo: 'losing',
  encontrando: 'finding', buscando: 'looking for',
  dejando: 'leaving', pasando: 'passing / happening',
  siguiendo: 'following', llamando: 'calling', llegando: 'arriving',
  creyendo: 'believing', bailando: 'dancing', cantando: 'singing',
  mirando: 'looking at', escuchando: 'listening',
  corriendo: 'running', cayendo: 'falling', muriendo: 'dying',
  jugando: 'playing', ganando: 'winning / earning',
  usando: 'using', intentando: 'trying', terminando: 'finishing',
  comenzando: 'starting', tomando: 'taking / drinking',
  bebiendo: 'drinking', gritando: 'shouting', llorando: 'crying',
  riendo: 'laughing', sonriendo: 'smiling', abrazando: 'hugging',
  besando: 'kissing', sonando: 'sounding / dreaming',
  gastando: 'spending', esperando: 'waiting / hoping',
  recordando: 'remembering', olvidando: 'forgetting',
  ayudando: 'helping', cambiando: 'changing', moviendo: 'moving',
  volando: 'flying', caminando: 'walking', trabajando: 'working',
  pagando: 'paying', luchando: 'fighting',
  sufriendo: 'suffering', disfrutando: 'enjoying',

  // ── Past participles ─────────────────────────────────────────────
  sido: 'been', estado: 'been (at/feeling)', tenido: 'had',
  hecho: 'done / made', ido: 'gone', venido: 'come',
  dicho: 'said', visto: 'seen', sabido: 'known',
  querido: 'wanted / dear', podido: 'been able to',
  puesto: 'put (past)', salido: 'gone out', llevado: 'carried',
  dado: 'given', traido: 'brought', hablado: 'spoken',
  comido: 'eaten', vivido: 'lived', pensado: 'thought',
  sentido: 'felt / sense', dormido: 'slept / asleep', perdido: 'lost',
  encontrado: 'found', buscado: 'looked for', dejado: 'left',
  pasado: 'passed / past', seguido: 'followed', llamado: 'called',
  llegado: 'arrived', creido: 'believed', bailado: 'danced',
  cantado: 'sung', mirado: 'looked at', escuchado: 'listened',
  corrido: 'run / corrido (song genre)', caido: 'fallen',
  muerto: 'dead / died', nacido: 'born', crecido: 'grown',
  ganado: 'won / earned', gastado: 'spent',
  olvidado: 'forgotten', recordado: 'remembered', amado: 'loved',
  besado: 'kissed', abrazado: 'hugged', roto: 'broken',
  abierto: 'opened', cerrado: 'closed', escrito: 'written',
  leido: 'read (past)', cambiado: 'changed', terminado: 'finished',
  herido: 'hurt / wounded',

  // ── Commands (imperative) ────────────────────────────────────────
  ve: 'he/she sees / go! (command)', haz: 'do / make (command)',
  ten: 'have (command)', pon: 'put (command)', sal: 'salt / leave! (command)',
  vete: 'go away', quedate: 'stay', sigueme: 'follow me',
  llamame: 'call me', besame: 'kiss me',
  abrazame: 'hug me', ayudame: 'help me', escuchame: 'listen to me',
  mirame: 'look at me', cuidate: 'take care of yourself',
  olvidame: 'forget me', perdoname: 'forgive me',
  olvidate: 'forget it / forget about it', espera: 'wait',
  mira: 'look', oye: 'hey / listen',
  anda: 'go ahead / come on', andale: 'go ahead / come on (Mexican)',
  orale: "okay / let's go (Mexican)",

  // ── Adverbs ───────────────────────────────────────────────────────
  no: 'no / not', tambien: 'also / too',
  tampoco: 'neither / not either', ya: 'already / now',
  todavia: 'still / yet', aun: 'still / yet / even',
  siempre: 'always', nunca: 'never', jamas: 'never',
  ahora: 'now', antes: 'before', despues: 'after / later',
  luego: 'then / later', pronto: 'soon', tarde: 'late / afternoon',
  temprano: 'early', hoy: 'today', ayer: 'yesterday',
  manana: 'tomorrow / morning', aqui: 'here', aca: 'here',
  alli: 'there', alla: 'over there', ahi: 'there',
  lejos: 'far', cerca: 'near', dentro: 'inside', fuera: 'outside',
  arriba: 'up / above', abajo: 'down / below',
  adelante: 'forward / ahead', atras: 'back / behind',
  bien: 'well / good', mal: 'bad / badly', muy: 'very',
  tan: 'so / as', tanto: 'so much', poco: 'little / few',
  mucho: 'much / a lot', casi: 'almost', solo: 'alone / only',
  tal: 'such', asi: 'like this / so', quizas: 'maybe', quiza: 'maybe',
  ademas: 'furthermore / besides', entonces: 'then / so',
  apenas: 'barely / just', incluso: 'even / including',
  recien: 'just (recently)', igual: 'same / equal',
  total: 'totally / in the end', claro: 'of course / clear',
  menos: 'less',

  // ── Common nouns ─────────────────────────────────────────────────
  amor: 'love', corazon: 'heart', vida: 'life',
  tiempo: 'time / weather', noche: 'night', dia: 'day',
  ano: 'year', vez: 'time (occasion)', casa: 'house / home',
  mundo: 'world', persona: 'person', hombre: 'man', mujer: 'woman',
  nino: 'child / boy', nina: 'girl / child',
  chico: 'boy / young man', chica: 'girl / young woman',
  amigo: 'friend (male)', amiga: 'friend (female)', familia: 'family',
  madre: 'mother', padre: 'father', mama: 'mom', papa: 'dad',
  hijo: 'son', hija: 'daughter', hermano: 'brother',
  hermana: 'sister', esposo: 'husband', esposa: 'wife',
  novio: 'boyfriend', novia: 'girlfriend',
  boca: 'mouth', ojo: 'eye', ojos: 'eyes', cara: 'face',
  mano: 'hand', manos: 'hands', cuerpo: 'body', cabeza: 'head',
  pelo: 'hair', piel: 'skin', voz: 'voice', alma: 'soul',
  mente: 'mind', sueno: 'dream / sleep / I dream',
  cancion: 'song', musica: 'music',
  baile: 'dance / I danced', fiesta: 'party',
  calle: 'street', ciudad: 'city', pais: 'country',
  tierra: 'land / earth', cielo: 'sky / heaven', mar: 'sea',
  agua: 'water', fuego: 'fire', luz: 'light', sol: 'sun',
  luna: 'moon', dinero: 'money', oro: 'gold',
  plata: 'silver / money (slang)', trabajo: 'work / job',
  problema: 'problem',
  cosa: 'thing', lugar: 'place', momento: 'moment',
  forma: 'form / way', parte: 'part', lado: 'side',
  tipo: 'type / guy', punto: 'point', fin: 'end',
  principio: 'beginning', historia: 'history / story',
  verdad: 'truth', mentira: 'lie', palabra: 'word',
  nombre: 'name', numero: 'number', hora: 'hour / time',
  minuto: 'minute', segundo: 'second / instant', semana: 'week',
  mes: 'month', nada: 'nothing', algo: 'something',
  todo: 'everything / all', todos: 'everyone / all',
  nadie: 'nobody', alguien: 'someone', dios: 'God',
  diablo: 'devil', manera: 'way / manner', gente: 'people',
  rey: 'king', reina: 'queen', bebe: 'baby',
  lagrima: 'tear', lagrimas: 'tears', dolor: 'pain / ache',
  miedo: 'fear', alegria: 'joy / happiness', tristeza: 'sadness',
  felicidad: 'happiness', esperanza: 'hope', fuerza: 'strength',
  libertad: 'freedom', paz: 'peace', guerra: 'war',
  sangre: 'blood', pecho: 'chest', brazo: 'arm',
  pierna: 'leg', pie: 'foot', dedo: 'finger / toe',
  labio: 'lip', labios: 'lips', cintura: 'waist',
  cadera: 'hip', caderas: 'hips', cuello: 'neck',
  espalda: 'back', rodilla: 'knee', hombro: 'shoulder',
  nariz: 'nose', oido: 'ear / hearing', oreja: 'ear',
  diente: 'tooth', dientes: 'teeth', carro: 'car',
  coche: 'car', auto: 'car', avion: 'airplane',
  barco: 'ship / boat', tren: 'train',
  bar: 'bar', club: 'club', disco: 'disco / album',
  cerveza: 'beer', trago: 'drink (alcoholic)',
  copa: 'glass / cup', ron: 'rum', tequila: 'tequila',
  champan: 'champagne', droga: 'drug', pistola: 'gun', bala: 'bullet',
  jefe: 'boss', enemigo: 'enemy', suerte: 'luck',
  exito: 'success / hit (song)', fama: 'fame',
  premio: 'prize', regalo: 'gift', viaje: 'trip',
  playa: 'beach', piscina: 'pool', isla: 'island',
  paraiso: 'paradise', infierno: 'hell', angel: 'angel',
  demonio: 'demon', ritmo: 'rhythm', melodia: 'melody',
  letra: 'lyrics / letter', coro: 'chorus', verso: 'verse',
  nota: 'note', pista: 'track / beat', beat: 'beat',
  lluvia: 'rain', viento: 'wind', nube: 'cloud', nubes: 'clouds',
  tormenta: 'storm', nieve: 'snow', calor: 'heat',
  arbol: 'tree', flor: 'flower', flores: 'flowers',
  rosa: 'rose / pink', rio: 'river', lago: 'lake',
  montana: 'mountain', selva: 'jungle', bosque: 'forest',
  campo: 'field / countryside', estrella: 'star', estrellas: 'stars',
  planeta: 'planet', universo: 'universe',
  comida: 'food', leche: 'milk', cafe: 'coffee / brown',
  pan: 'bread', arroz: 'rice', pollo: 'chicken',
  carne: 'meat', pescado: 'fish', fruta: 'fruit',
  verdura: 'vegetable', azucar: 'sugar',
  telefono: 'phone', celular: 'cell phone', foto: 'photo',
  pantalla: 'screen', red: 'network / web',
  pareja: 'couple / partner', relacion: 'relationship',
  promesa: 'promise', perdon: 'forgiveness / sorry',
  disculpa: 'excuse me / apology', pelea: 'fight / argument',
  celos: 'jealousy', traicion: 'betrayal', traidor: 'traitor',
  dano: 'damage / harm', culpa: 'fault / blame',
  engano: 'deception', cicatriz: 'scar', herida: 'wound / hurt',
  cadena: 'chain / necklace', anillo: 'ring', pulsera: 'bracelet',
  reloj: 'watch / clock', ropa: 'clothes', zapatos: 'shoes',
  tenis: 'sneakers', camisa: 'shirt', vestido: 'dress',
  perfume: 'perfume', maquillaje: 'makeup',
  coraje: 'courage / anger', orgullo: 'pride',
  vergüenza: 'shame', pena: 'pity / shame / sorrow',
  carino: 'affection / darling', amante: 'lover',
  tesoro: 'treasure / darling', rancho: 'ranch / small town',
  camioneta: 'truck / van', troca: 'truck (Mexican-American slang)',
  palacio: 'palace', trofeo: 'trophy', corona: 'crown',
  villa: 'villa', sicario: 'hitman', cartel: 'cartel',
  gatillo: 'trigger', banda: 'gang / band / crew',
  raza: 'people / race / crew', candela: 'fire / candle / hot (slang)',
  hay: 'there is / there are', habia: 'there was / there were',
  habra: 'there will be',

  // ── Adjectives ───────────────────────────────────────────────────
  bueno: 'good', malo: 'bad', buen: 'good', grande: 'big / great',
  pequeno: 'small / little', largo: 'long', corto: 'short',
  alto: 'tall / high', nuevo: 'new', viejo: 'old', joven: 'young',
  hermoso: 'beautiful', hermosa: 'beautiful',
  bonito: 'pretty / nice', bonita: 'pretty / nice',
  lindo: 'pretty / cute', linda: 'pretty / cute',
  bello: 'beautiful', bella: 'beautiful', feo: 'ugly',
  rico: 'rich / delicious', rica: 'rich / delicious', pobre: 'poor',
  feliz: 'happy', triste: 'sad', contento: 'happy / content',
  alegre: 'cheerful / happy', enojado: 'angry', asustado: 'scared',
  cansado: 'tired', loco: 'crazy', loca: 'crazy', libre: 'free',
  seguro: 'safe / sure', peligroso: 'dangerous', fuerte: 'strong',
  debil: 'weak', rapido: 'fast', lento: 'slow',
  dificil: 'difficult', facil: 'easy', importante: 'important',
  diferente: 'different', mismo: 'same', misma: 'same',
  juntos: 'together', juntas: 'together', cada: 'each / every',
  otro: 'other / another', otra: 'other / another',
  otros: 'others', otras: 'others', mucha: 'much / a lot',
  muchos: 'many', muchas: 'many', poca: 'little',
  pocos: 'few', pocas: 'few', mejor: 'better / best',
  peor: 'worse / worst', mayor: 'greater / older',
  menor: 'lesser / younger', primero: 'first',
  ultimo: 'last', siguiente: 'next / following',
  cierto: 'certain / true', oscuro: 'dark',
  negro: 'black', blanco: 'white', rojo: 'red', azul: 'blue',
  verde: 'green', amarillo: 'yellow', rosado: 'pink',
  morado: 'purple', gris: 'gray', dorado: 'golden',
  plateado: 'silver', frio: 'cold', suave: 'soft / smooth',
  duro: 'hard / tough', dulce: 'sweet', amargo: 'bitter',
  salado: 'salty', buena: 'good', mala: 'bad',
  nueva: 'new', vieja: 'old', natural: 'natural',
  especial: 'special', normal: 'normal', final: 'final / end',
  posible: 'possible', imposible: 'impossible',
  increible: 'incredible', terrible: 'terrible',
  horrible: 'horrible', invisible: 'invisible',
  celoso: 'jealous', celosa: 'jealous', infiel: 'unfaithful',
  fiel: 'faithful', inocente: 'innocent', culpable: 'guilty',
  sutil: 'subtle', sensual: 'sensual', sexy: 'sexy',
  enamorado: 'in love', enamorada: 'in love',
  confundido: 'confused', sorprendido: 'surprised',
  aburrido: 'bored', emocionado: 'excited', nervioso: 'nervous',
  tranquilo: 'calm / peaceful', ocupado: 'busy',
  listo: 'ready / smart', lista: 'ready / list',
  rota: 'broken', bendito: 'blessed', maldito: 'damned',
  precioso: 'precious / beautiful', preciosa: 'precious / beautiful',
  chido: 'cool (Mexican slang)', chida: 'cool (Mexican slang)',
  brutal: 'brutal / awesome (slang)', chevere: 'cool (Caribbean)',
  fregon: 'awesome / badass (Mexican)',

  // ── Numbers ──────────────────────────────────────────────────────
  uno: 'one', dos: 'two', tres: 'three', cuatro: 'four',
  cinco: 'five', seis: 'six', siete: 'seven', ocho: 'eight',
  nueve: 'nine', diez: 'ten', once: 'eleven', doce: 'twelve',
  cien: 'one hundred', mil: 'one thousand', millon: 'million',

  // ── Greetings / expressions ───────────────────────────────────────
  gracias: 'thank you', favor: 'please / favor',
  hola: 'hello', adios: 'goodbye', buenas: 'hi (greeting)',
  exacto: 'exactly', ay: 'oh / ouch', uy: 'wow / ooh',
  dale: 'go ahead / okay / come on', okay: 'okay',

  // ── Urban / reggaeton slang ───────────────────────────────────────
  mami: 'baby girl / sweetie / mama',
  papi: 'baby boy / sweetie / daddy',
  nena: 'girl / baby girl', nene: 'boy / baby boy',
  jeva: 'girl (Caribbean slang)', titi: 'girl (Puerto Rican slang)',
  perreo: 'reggaeton-style dancing',
  bichota: 'boss lady / powerful woman',
  bicho: 'bug / guy / thing (slang)', flow: 'flow / style',
  jangueo: 'hangout (slang)', panas: 'friends (Venezuelan)',
  pana: 'friend / buddy', cabron: 'bastard / tough guy (vulgar)',
  perrea: 'she dances reggaeton', bebecita: 'little baby girl',
  mamacita: 'hot woman / sweetie',
  gatita: 'kitty / term of endearment', gato: 'cat',
  gata: 'cat / girl (slang)', conejo: 'rabbit',
  broki: 'bro / buddy (slang)', wey: 'dude (Mexican)',
  guey: 'dude (Mexican)', morro: 'kid / boy (Mexican)',
  morra: 'girl (Mexican slang)', neta: 'truth / for real (Mexican)',
  feria: 'money (Mexican slang)', varo: 'money (Mexican slang)',
  ranfla: 'car (Mexican slang)', jale: 'work / deal (Mexican)',
  carnal: 'bro / homeboy (Mexican)', vato: 'dude / guy (Mexican)',
  lana: 'money (Mexican slang)',
  guero: 'light-skinned / blond (Mexican)', onda: 'vibe / wave',
  paisa: 'compatriot / fellow Mexican', compa: 'buddy / companion',
  compas: 'friends / buddies', pendejo: 'idiot / fool (vulgar)',
  tusa: 'heartbreak / heartache', hechizo: 'spell / charm',
  trampa: 'trap', bruja: 'witch', santos: 'saints',
  pisteo: 'drinking session (Mexican slang)',
  pisto: 'drink / alcohol (Mexican)',
  salsa: 'salsa (music / food)', merengue: 'merengue',
  cumbia: 'cumbia', bachata: 'bachata',
  reggae: 'reggae', rap: 'rap', trap: 'trap (music)',
};

// Build a secondary index without accents so "tambien" finds "también" entry
const UNACCENTED = {};
for (const [k, v] of Object.entries(DICT)) {
  const plain = k.normalize('NFD').replace(/[̀-ͯ]/g, '');
  if (plain !== k && !(plain in DICT)) UNACCENTED[plain] = v;
}

export function lookupLocal(word) {
  if (!word) return null;
  const lower = word.toLowerCase().trim();
  return DICT[lower] ?? UNACCENTED[lower] ?? null;
}
